### ISSUE TITLE
Why 0.1 + 0.2 === 0.30000000000000004 ???

### ISSUE THREAD

**Issue by edysegura** [edysegura/js-weird#1]
Why don’t my numbers add up?

So you’ve written some absurdly simple code, say for example:

	0.1 + 0.2

and got a really unexpected result:

	0.30000000000000004

Ref.: http://floating-point-gui.de/

**Comment by rafadpedrosa** [comment]
**In your own ref**

_"It’s not stupid, just different. Decimal numbers cannot accurately represent a number like 1/3"_

http://floating-point-gui.de/formats/binary/
